#!/bin/bash
usage()
{
cat << EOF

Show dirty git repos states under a path

OPTIONS:
    -h      show usage info
    -p      path to search
    -q      do not output files
    -s      no progress spinner

EOF
exit 1
}

spinner()
{
  spin='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
  # spin='⠋⠙⠚⠞⠖⠦⠴⠲⠳⠓'
  # spin='⠄⠆⠇⠋⠙⠸⠰⠠⠰⠸⠙⠋⠇⠆'
  # spin='⠋⠙⠚⠒⠂⠂⠒⠲⠴⠦⠖⠒⠐⠐⠒⠓⠋'
  # spin='⠁⠉⠙⠚⠒⠂⠂⠒⠲⠴⠤⠄⠄⠤⠴⠲⠒⠂⠂⠒⠚⠙⠉⠁'
  # spin='⠈⠉⠋⠓⠒⠐⠐⠒⠖⠦⠤⠠⠠⠤⠦⠖⠒⠐⠐⠒⠓⠋⠉⠈'
  # spin='⠁⠁⠉⠙⠚⠒⠂⠂⠒⠲⠴⠤⠄⠄⠤⠠⠠⠤⠦⠖⠒⠐⠐⠒⠓⠋⠉⠈⠈⠉'
  pid=$1
  msg='';
  if [ ! -z "$2" ];then
    msg="$2 "
  fi
  let spin_len=${#spin};
  i=0
  while kill -0 $pid 2>/dev/null
  do
    i=$(( (i+1) %${spin_len}  ))
    printf "\r${spin:$i:1} $msg"
    sleep .1
  done
}

while getopts "hqp:s" option
do
  case $option in
    h) usage;;
    q) QUIET=1;;
    p) SEARCH_PATH=$OPTARG;;
    s) NO_SPINNER=1;;
    \?) usage;exit 2;;
  esac
done

count_all=0;
count_clean=0;
count_dirty=0;

if [ -z "$SEARCH_PATH" ];then

  if [ -z "$1" ];then
    SEARCH_PATH='.'
  else
    SEARCH_PATH="$1"
  fi
fi

find_states(){
  for gitdir in `find $SEARCH_PATH -name .git`;
    do
      let count_all=$count_all+1;
      workTree=${gitdir%/*};

      if [[ "$(git --git-dir=$gitdir --work-tree=$workTree status 2> /dev/null | tail -n1 | cut -c 1-17)" != "nothing to commit" ]];then
        let count_dirty=$count_dirty+1;
        if [ "$workTree" == "." ];then
          echo -e "\r "
        else
          echo -e "\r$workTree";
        fi
        if [ "$QUIET" != "1" ];then
          git --git-dir=$gitdir --work-tree=$workTree status -sb;
          echo ""
        fi
      else
        let count_clean=$count_clean+1;
      fi
  done
  echo -e "\rREPOS:$count_all  DIRTY:$count_dirty  CLEAN:$count_clean";
}

if [ "$NO_SPINNER" == "1" ];then
  find_states
else
  find_states &
  spinner $!
fi

exit 0
